<?php

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0-SNAPSHOT
 */

namespace winwin\discovery\apisix\servant;

use wenbinye\tars\protocol\annotation\TarsServant;
use wenbinye\tars\protocol\annotation\TarsParameter;
use wenbinye\tars\protocol\annotation\TarsReturnType;

/**
 * @TarsServant(name="EventBusSubscriberObj")
 */
interface EventBusSubscriberServant
{
    /**
     * @TarsParameter(name = "notification", type = "Notification")
     * @TarsReturnType(type = "void")
     *
     * @param \winwin\discovery\apisix\servant\Notification $notification
     * @return void
     */
    public function handle($notification);

}
